// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Apkzi: typeof import('./src/view/apkzi/Apkzi.vue')['default']
    ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    LoginForm: typeof import('./src/components/loginform/LoginForm.vue')['default']
    MainMenu: typeof import('./src/components/mainmenu/MainMenu.vue')['default']
    PartComboBox: typeof import('./src/components/mainmenu/partcombobox/PartComboBox.vue')['default']
    Pc: typeof import('./src/view/pc/Pc.vue')['default']
    Pki: typeof import('./src/view/pki/Pki.vue')['default']
    PkiTable: typeof import('./src/view/pki/pkitable/PkiTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemCases: typeof import('./src/view/systemcases/SystemCases.vue')['default']
    TextCell: typeof import('./src/components/table/inputcell/TextCell.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
